config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  get 'mypage', to: 'welcome#mypage'
  get 'signout', to: 'welcome#signout'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  resources :addresses, only: [:edit, :update]

  resources :welcome, only: [:index]
  resources :purchases, only: [:index]

  resources :items do
    resources :purchases, only: [:new, :create]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :cards, only: [:show, :new, :create, :destroy]
  
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  require 'payjp'
  before_action :authenticate_user!, :set_category, :set_cards
  before_action :set_item, except: [:index]
  before_action :payjp_api, except: [:new]

  def index
  end
  
  def new
    if @cards.exists?
      @purchase = Purchase.new
      card = @cards.first
      customer = Payjp::Customer.retrieve(card.customer_id)
      @card_info = customer.cards.retrieve(card.card_id)
      @address = Address.where(user_id: current_user.id).take
    else
      redirect_to new_card_path
    end
  end

  def create
    charge = Payjp::Charge.create(
      :amount => @item.price,
      :customer => current_user.cards.first.customer_id,
      :currency => 'jpy'
    )

    @purchase = Purchase.new(purchase_params)
    if @purchase.save
      redirect_to root_path, notice: '商品を購入しました。'
    else
      redirect_to item_confirmation_path(@item.id)
    end

  end

  private

  def set_category
    @parents = Category.where(ancestry: nil)
  end

  def payjp_api
    Payjp.api_key = Rails.application.credentials[:payjp_secret_key]
  end

  def set_cards
    @cards = Card.where(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def purchase_params
    params.permit(:item_id).merge(user_id: current_user.id)
  end

end

app/views/purchases/index.html.haml
= render 'shared/header'
.UserMyPage
  .UserMyPage__content
    = render 'welcome/sidebar'
    .UserMyPage__content__main
      .UserItemsPage
        .UserItemsPage__SelectTab
          .UserItemsPage__SelectTab__sell
            =link_to '出品した商品', welcome_index_path, class: 'UserItemsPage__SelectTab__sell__text'
          .UserItemsPage__SelectTab__buy
            %h1.UserItemsPage__SelectTab__buy__text 購入した商品
        .UserItemsPage__content
          .UserItemsPage__content__label
            %h2.UserItemsPage__content__label__date 購入日
            %h2.UserItemsPage__content__label__name 商品名
            %h2.UserItemsPage__content__label__price 値段
          .UserItemsPage__conntent__ItemList
            - current_user.purchases.each do |purchase|
              .UserItemsPage__content__ItemList__item
                .UserItemsPage__content__ItemList__item__date
                  = purchase.created_at.strftime("%Y/%m/%d")
                .UserItemsPage__content__ItemList__item__name
                  = purchase.item.product_name
                .UserItemsPage__content__ItemList__item__price
                  ¥
                  = purchase.item.price
.fixedButton
  %p 出品する
  .fixedButton__image
    = link_to new_item_path do
      =image_tag('icon/icon_camera.png', alt: "出品ボタン")
= render 'shared/bottomBanner'
= render 'shared/footer'

app/views/purchases/new.html.haml
.PurcahseConfirmPage
  .PurchaseConfirmPage__header
    .PurchaseConfirmPage__header__icon
      = link_to root_path do
        = image_tag('logo/logo.png', alt: "ヘッダーロゴ")
  .PurchaseConfirmPage__content
    .Confirmation
      %h1.Confirmation__title1 購入内容の確認
      .Underline
      %h2.Confirmation__title2 購入商品
      .Confirmation__item
        .Confirmation__item__Info
          .Confirmation__item__Info__image
            = image_tag @item.item_images[0].src.url
        .Confirmation__item__Detail
          %h3.Confirmation__item__Detail__name
            = @item.product_name
          %h3.Confirmation__item__Detail__price
            送料込み（税込み）¥
            = @item.price
      .Underline
      .Confirmation__Cost
        %h2.Confirmation__Cost__title 支払い金額
        .Confirmation__Cost__content
          %h2.Confirmation__Cost__content__expense
            ¥
            = @item.price
      .Underline
      %h2.Confirmation__title2 支払い方法
      .Confirmation__Card
        .Confirmation__Card__content
          %h3.Confirmation__Card__content__text クレジットカード
          .Confirmation__Card__content__Info
            %h3.brand
              = @card_info.brand
            %h3.number
              **** **** ****
              = @card_info.last4
          .Confirmation__Card__content__Expiration
            %h3.Confirmation__Card__content__Expiration__text 有効期限
            %h3.Confirmation__Card__content__Expiration__month
              = sprintf("%02d", @card_info.exp_month)
            %h3 /
            %h3.Confirmation__Card__content__Expiration__year
              = @card_info.exp_year - 2000
        .Confirmation__Card__change
          = link_to '変更する', card_path(@cards.first.id), method: :get, class: 'Confirmation__Card__change__btn'
      .Underline
      %h2.Confirmation__title2 配送先住所
      .Confirmation__Address
        .Confirmation__Address__content
          %h3.Confirmation__Address__content__postcode
            〒
            = @address.postcode
          %h3.Address__content__ad
            = Prefecture.find(@address.prefecture_id).name + @address.city + @address.block + @address.building
        .Confirmation__Address__change
          = link_to '変更する', edit_address_path(current_user.address.id), method: :get, class: 'Confirmation__Address__change__btn'
      .Underline
      .Confirmation__submit
        = form_with model: [@item, @purchase] do |f|
          .Confirmation__submit__button
            = f.submit '購入する', class: 'Confirmation__submit__button__btn'
  .PurchaseConfirmPage__footer
    .PurchaseConfirmPage__footer__icon
      = link_to root_path do
        = image_tag('logo/logo.png', alt: "フッターロゴ")