config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  get 'mypage', to: 'welcome#mypage'
  get 'signout', to: 'welcome#signout'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  resources :addresses, only: [:edit, :update]

  resources :welcome, only: [:index]
  resources :purchases, only: [:index]

  resources :items do
    resources :purchases, only: [:new, :create]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :cards, only: [:show, :new, :create, :destroy]
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
before_action :authenticate_user!, :set_category
  def index
  end

  def set_category
    @parents = Category.where(ancestry: nil)
  end
end

app/views/welcome/_sidebar.html.haml
.UserMyPage__content__sidebar
  .link.PageTitle
    = link_to 'マイページトップ', mypage_path, class: 'text'
    .icon.fas.fa-angle-right
  .link
    = link_to '出品する', new_item_path, class: 'text'
    .icon.fas.fa-angle-right
  .link
    = link_to '出品した商品一覧・商品の編集', welcome_index_path, class: 'text'
    .icon.fas.fa-angle-right
  .link
    = link_to '購入した商品一覧', purchases_path, class: 'text'
    .icon.fas.fa-angle-right
  .link
    = link_to 'クレジットカードの登録・削除', new_card_path, class: 'text'
    .icon.fas.fa-angle-right
  .link
    = link_to 'プロフィール', '#', class: 'text'
    .icon.fas.fa-angle-right
  .link
    = link_to '届け先住所の変更', edit_address_path(current_user.address.id), class: 'text'
    .icon.fas.fa-angle-right
  .link
    = link_to 'ログアウト', signout_path, method: :get, class: 'text'
    .icon.fas.fa-angle-right

app/views/welcome/index.html.haml
= render 'shared/header'
.UserMyPage
  .UserMyPage__content
    = render 'sidebar'
    .UserMyPage__content__main
      .UserItemsPage
        .UserItemsPage__SelectTab
          .UserItemsPage__SelectTab__sell
            %h1.UserItemsPage__SelectTab__sell__text 出品した商品
          .UserItemsPage__SelectTab__buy
            =link_to '購入した商品', purchases_path, class: 'UserItemsPage__SelectTab__buy__text'
        .UserItemsPage__content
          .UserItemsPage__content__label
            %h2.UserItemsPage__content__label__date 出品日
            %h2.UserItemsPage__content__label__name 商品名
            %h2.UserItemsPage__content__label__price 値段
            %h2.UserItemsPage__content__label__status 状態
            %h2.UserItemsPage__content__label__sold 売却日
          .UserItemsPage__conntent__ItemList
            - current_user.items.each do |item|
              .UserItemsPage__content__ItemList__item
                .UserItemsPage__content__ItemList__item__date
                  = item.created_at.strftime("%Y/%m/%d")
                .UserItemsPage__content__ItemList__item__name
                  = item.product_name
                .UserItemsPage__content__ItemList__item__price
                  ¥
                  = item.price
                .UserItemsPage__content__ItemList__item__status
                  - if item.purchase.blank?
                    %h2.UserItemsPage__content__ItemList__item__status__onsale 出品中
                  - else
                    %h2.UserItemsPage__content__ItemList__item__status__soldout 売却済み
                .UserItemsPage__content__ItemList__item__delete
                  - if item.purchase.blank?
                    .UserItemsPage__content__ItemList__item__delete__button
                      = link_to '商品を編集する', edit_item_path(item.id), class: 'UserItemsPage__content__ItemList__item__delete__button__btn'
                  - else
                    .UserItemsPage__content__ItemList__item__delete__button
                      = item.purchase.created_at.strftime("%Y/%m/%d")
.fixedButton
  %p 出品する
  .fixedButton__image
    = link_to new_item_path do
      =image_tag('icon/icon_camera.png', alt: "出品ボタン")
= render 'shared/bottomBanner'
= render 'shared/footer'

app/views/welcome/mypage.html.haml
= render 'shared/header'
.UserMyPage
  .UserMyPage__content
    = render 'sidebar'
    .UserMyPage__content__main
.fixedButton
  %p 出品する
  .fixedButton__image
    = link_to 'items/new' do
      =image_tag('icon/icon_camera.png', alt: "出品ボタン")
= render 'shared/bottomBanner'
= render 'shared/footer'

app/views/welcome/signout.html.haml
= render 'shared/header'
.UserMyPage
  .UserMyPage__content
    = render 'sidebar'
    .UserMyPage__content__main
      .SignoutButton
        = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'SignoutButton__btn'
.fixedButton
  %p 出品する
  .fixedButton__image
    = link_to 'items/new' do
      =image_tag('icon/icon_camera.png', alt: "出品ボタン")
= render 'shared/bottomBanner'
= render 'shared/footer'