config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  get 'mypage', to: 'welcome#mypage'
  get 'signout', to: 'welcome#signout'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  resources :addresses, only: [:edit, :update]

  resources :welcome, only: [:index]
  resources :purchases, only: [:index]

  resources :items do
    resources :purchases, only: [:new, :create]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :cards, only: [:show, :new, :create, :destroy]
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images, allow_destroy: true
  belongs_to :user
  belongs_to :brand, optional: true, dependent: :destroy
  accepts_nested_attributes_for :brand, allow_destroy: true
  has_one :purchase
  belongs_to :category, optional: true
  
extend ActiveHash::Associations::ActiveRecordExtensions
belongs_to_active_hash :condition
belongs_to_active_hash :ShippingFee
belongs_to_active_hash :DayToShip
belongs_to_active_hash :prefecture

validates :item_images, presence: { message: "を選択してください。" }
validates :item_images, length: { minimum: 1, too_short: "は1枚以上選択してください" }
validates :item_images, length: { maximum: 5, too_long: "は5枚以下選択してください" }
validates :product_name, presence: { message: "を入力してください。" }
validates :description, presence: { message: "を入力してください。" }
validates :category_id, presence: { message: "を選択してください。" }
validates :condition_id, presence: { message: "を選択してください。" }
validates :shipping_fee_id, presence: { message: "を選択してください。" }
validates :prefecture_id, presence: { message: "を選択してください。" }
validates :day_to_ship_id, presence: { message: "を選択してください。" }
validates :price, presence: { message: "を入力してください。" }
validates :user_id, presence: { message: "ログインしてください"}

validates :price, format: {with: /\A[0-9０-９]+\z/}
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :set_category, only: [:new, :create, :show, :index, :edit, :update]
  before_action :set_item, only: [:show, :destroy, :edit, :update]


  #jsonで親の名前で検索し、紐づく小カテゴリーの配列を取得
  def get_category_children
    @category_children = Category.find(params[:parent_name]).children
  end

  #jsonで子カテゴリーに紐づく孫カテゴリーの配列を取得
  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  # 商品一覧
  def index
    @parents = Category.where(ancestry: nil)
    @items = Item.all.order(created_at: :desc)
    @brandItems = Item.where(brand_id: Brand.where.not(brand_name: "").ids).order(created_at: :desc)
    @nobrandItems = Item.where(brand_id: Brand.where(brand_name: "").ids).order(created_at: :desc)
  end

  # 商品出品
  def new
    flash[:notice] = "ログイン済みユーザーのみ出品できます" unless user_signed_in?
    @item = Item.new
    @item_images = @item.item_images.build
    @item.build_brand
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = '出品に成功しました'
      redirect_to root_path
    else
      unless @item.item_images.present?
        @item.item_images.new
        render 'new'
      else
        render 'new'
      end
    end
  end

  # 商品情報編集
  def edit
    #カテゴリーデータ取得
    @grandchild_category = @item.category
    @child_category = @grandchild_category.parent 
    @category_parent = @child_category.parent

    #カテゴリー一覧を作成
    @category = Category.find(params[:id])
    # 紐づく孫カテゴリーの親（子カテゴリー）の一覧を配列で取得
    @category_children = @item.category.parent.parent.children
    # 紐づく孫カテゴリーの一覧を配列で取得
    @category_grandchildren = @item.category.parent.children

    if user_signed_in? && @item.user_id == current_user.id

    else
      redirect_to root_path, alert: "出品した商品ではありません"
    end

  end

  def update
    @parents = Category.where(ancestry: nil)
    # binding.pry
    if @item.update(item_params)
      flash[:notice] = "編集が完了しました"
      redirect_to root_path
    else
        #カテゴリーデータ取得
      @grandchild_category = @item.category
      @child_category = @grandchild_category.parent 
      @category_parent = @child_category.parent

      #カテゴリー一覧を作成
      @category = Category.find(params[:id])
      # 紐づく孫カテゴリーの親（子カテゴリー）の一覧を配列で取得
      @category_children = @item.category.parent.parent.children
      # 紐づく孫カテゴリーの一覧を配列で取得
      @category_grandchildren = @item.category.parent.children
      render :edit, alert: "商品を更新できませんでした"
      # redirect_to edit_item_path(@item), alert: @item.errors.full_messages
    end
  end
  
  def show
    @parents = Category.where(ancestry: nil)
    @purchase = @item.purchase
    @category_id = @item.category_id
    @category_parent = Category.find(@category_id).parent.parent
    @category_child = Category.find(@category_id).parent
    @category_grandchild = Category.find(@category_id)
    @user_nickname = User.where(id: @item.user_id)[0].nickname
  end

  def destroy
    if @item.destroy
      redirect_to root_path, notice: '出品を取り消しました。'
    else
      redirect_to welcome_index_path
    end
  end
  
  private
  # 親カテゴリー
  def set_category
    @parents = Category.where(ancestry: nil)
  end

  def set_item
    if Item.ids.include?(params[:id].to_i)
      @item = Item.find(params[:id])
    else
      redirect_to root_path
    end
  end
  
  def item_params
    params.require(:item).permit(
      :product_name, :description, :category_id, :condition_id, :shipping_fee_id, :prefecture_id, :day_to_ship_id, :price, item_images_attributes: [:src, :_destroy, :id], brand_attributes: [:brand_name, :id]
    ).merge(user_id: current_user.id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item_list.html.haml
- @nobrandItems.first(5).each do |item|
  - if user_signed_in? && item.user_id == current_user.id
    = link_to edit_item_path(item.id) do
      .lists__product
        = image_tag item.item_images[0].src.url
        .product__detail
          %h3.product__detail--name
            = item.product_name
          %ul
            -if item.purchase == nil
              %li.product__detail--price 
                = item.price
                円
                .product__detail--tax
                (税込)
            -else
              .SoldOut SOLD OUT
  - else
    = link_to item_path(item.id) do
      .lists__product
        = image_tag item.item_images[0].src.url
        .product__detail
          %h3.product__detail--name
            = item.product_name
          %ul
            -if item.purchase == nil
              %li.product__detail--price 
                = item.price
                円
                .product__detail--tax
                (税込)
            -else
              .SoldOut SOLD OUT

app/views/items/_item_list_with_brand.html.haml
- @brandItems.first(5).each do |item|
  - if user_signed_in? && item.user_id == current_user.id
    = link_to edit_item_path(item.id) do
      .lists__product
        = image_tag item.item_images[0].src.url
        .product__detail
          %h3.product__detail--name
            = item.product_name
          %ul
            -if item.purchase == nil
              %li.product__detail--price 
                = item.price
                円
                .product__detail--tax
                (税込)
            -else
              .SoldOut SOLD OUT
  - else
    = link_to item_path(item.id) do
      .lists__product
        = image_tag item.item_images[0].src.url
        .product__detail
          %h3.product__detail--name
            = item.product_name
          %ul
            -if item.purchase == nil
              %li.product__detail--price 
                = item.price
                円
                .product__detail--tax
                (税込)
            -else
              .SoldOut SOLD OUT

app/views/items/edit.html.haml
.SellingPage
  .SellingPage__header
    .SellingPage__header__icon
      = link_to root_path do
        = image_tag('logo/logo.png', alt: "ヘッダーロゴ")
  .SellingPage__content
    .SellingPage__content__form
      = form_for(@item) do |f|
        = render 'shared/error_form', locals: { item: @item }
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 出品画像
              .FormField__label__title--must 必須

          %h1 最大5枚までアップロードできます
          .post__drop__box__container
            .prev-content
              //JSで挿入したhtmlと同じ形 each文でのプレビュー表示
              - @item.item_images.each do |image|
                .preview-box
                  .upper-box
                    = image_tag image.src.url, width: "112", height: "112", alt: "preview"
                  .lower-box
                    .delete-box
                      .delete-btn
                        %span 削除
            .label-content
              
              //プレビューの数に合わせてforオプションを指定
              = f.label :"item_images_attributes_#{@item.item_images.length}_src", class: "label-box", id: "label-box--#{@item.item_images.length}" do
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :item_images do |i|

                //プレビューが出ている分のfile_fieldとdelete用のチェックボックスを設置
                = i.file_field :src, type:"file", class: "hidden-field"
                = i.check_box :_destroy, class: "hidden-checkbox"

                //5つのfile_fieldを準備するに当たって、足りない分を表示
              - @item.item_images.length.upto(4) do |i|
                %input{name: "item[item_images_attributes][#{i}][src]", id: "item_item_images_attributes_#{i}_src", class:"hidden-field", type:"file"}

        .Underline
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 商品名
              .FormField__label__title--must 必須
          .FormField__input
            = f.text_field :product_name, class: 'FormField__input--short', placeholder: '40文字まで'
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 商品の説明
              .FormField__label__title--must 必須
          .FormField__input
            = f.text_area :description, class: 'FormField__input--long', placeholder: '商品の説明（必須1,000文字以内)&#13;&#10;(色、素材、重さ、定価、注意点など)&#13;&#10;&#13;&#10;例) 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。'.html_safe
        .Underline
        .FormField
          %h1 商品の詳細
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name カテゴリー
              .FormField__label__title--must 必須

          .FormField__input#category_box
            .pulldown#partent_box
              = f.collection_select :category_id, @parents.all, :id, :name, {include_blank: "選択してください", selected: @item.category&.root_id }, {class: "FormField__input--short", id: "parent_category", name: ""}

            .pulldown.item_input__body__category__children#children_box
              = f.collection_select :category_id, @category_children, :id, :name, {include_blank: "選択してください", selected: @item.category.parent.id }, {class: "FormField__input--short", id: "parent_category", name: ""}
            .pulldown.item_input__body__category__grandchildren#grandchildren_box
              = f.collection_select :category_id, @category_grandchildren, :id, :name, {include_blank: "選択してください"}, {class: "FormField__input--short", id: "parent_category", name: ""}

        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name ブランド
              .FormField__label__title--free 任意
          .FormField__input
            = f.fields_for :brand do |i|
              = i.text_field :brand_name, class: 'FormField__input--short', placeholder: '例）シャネル'
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 商品の状態
              .FormField__label__title--must 必須
          .FormField__input
            = f.collection_select :condition_id, Condition.all, :id, :name, {include_blank: "選択してください"}, {class: "FormField__input--short"}
        .Underline
        .FormField
          %h1 配送について
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 配送料の負担
              .FormField__label__title--must 必須
          .FormField__input
            = f.collection_select :shipping_fee_id, ShippingFee.all, :id, :name, {include_blank: "選択してください"}, {class: "FormField__input--short"}
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 発送元の地域
              .FormField__label__title--must 必須
          .FormField__input
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: "選択してください"}, {class: "FormField__input--short"}
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 発送までの日数
              .FormField__label__title--must 必須
          .FormField__input
            = f.collection_select :day_to_ship_id, DayToShip.all, :id, :name, {include_blank: "選択してください"}, {class: "FormField__input--short"}
        .Underline
        .FormField
          %h1 価格（¥300〜¥9,999,999）
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 販売価格
              .FormField__label__title--must 必須
            .FormField__label__price
              ¥
              = f.number_field :price, class: 'FormField__label__price__value'
        .Submit
          = f.submit '商品情報を更新', class: 'Submit__btn'
          = link_to '出品を取り消す', item_path(@item.id), class: 'Submit__destroy', method: :delete
        .Notice 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  .SellingPage__footer
    .SellingPage__footer__icon
      = link_to root_path do
        = image_tag('logo/logo.png', alt: "フッターロゴ")

app/views/items/index.html.haml
= render 'layouts/notifications'
= render 'shared/header'
.main
  %section.topbanner
    .topbanner__content
      %h2.topbanner__content--subtitle 人生を変えるフリマアプリ
      %p.topbanner__content--message
        FURIMAはだれでも簡単に出品・購入できる
        %br フリマアプリです
      .dlButton
        %a.dlButton__apple
          =image_tag('icon/appledownloadicon.svg', alt: "appstoreのアイコン")
        %a.dlButton__google
          =image_tag('icon/googledownloadicon.png', alt: "GooglePlayのアイコン")
  %section.topintroduction
    %h2.topintroduction__subtitle FURIMAが選ばれる3つの理由
    %ul.reasons
      %li.reasons__reason
        .reasons__reason--pic
          %span.number 1
          =image_tag('pict/pict-reason-01.jpg', alt: "理由1")
        %h3
          %span> 3分
          ですぐに出品
        %p スマホで入力するだけで簡単に出品できる！
      %li.reasons__reason
        .reasons__reason--pic
          %span.number 2
          =image_tag('pict/pict-reason-02.jpg', alt: "理由2")
        %h3 
          %span> シンプル 
          で使いやすい
        %p めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.reasons__reason
        .reasons__reason--pic
          %span.number 3
          =image_tag('pict/pict-reason-03.jpg', alt: "理由3")
        %h3 
          %span> 手数料 
          業界最安
        %p 最大3%でお得に出品&購入！
  %section.topmiddle
    .topmiddle__content
      %h2.topmiddle__content--subtitle 会員数日本一位
      %p.topmiddle__content--message 
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .dlButton
        %a.dlButton__apple
          =image_tag('icon/appledownloadicon.svg', alt: "appstoreのアイコン")
        %a.dlButton__google
          =image_tag('icon/googledownloadicon.png', alt: "GooglePlayのアイコン")

  %section.topfeatures
    %h2.topfeatures__subtitle FURIMAの特徴
    %ul.features
      %li.features__feature
        .features__feature--pic
          = image_tag('icon/icon-01.png', alt: "特徴1")
        %h3 簡単に売り買いできる
        %p スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.features__feature
        .features__feature--pic
          = image_tag('icon/icon-03.png', alt: "特徴2")
        %h3 売上金は即日振込みに対応
        %p 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %li.features__feature
        .features__feature--pic
          = image_tag('icon/icon-04.png', alt: "特徴3")
        %h3 様々な支払いに対応
        %p お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.pickupcontainer
    .pickupcontainer__head
      新着アイテム
    .pickupcontainer__productHead
      新規投稿商品
    .lists
      = render 'item_list'
                
  %section.pickupcontainer.padding-bottom
    .pickupcontainer__head
      ピックアップブランド
    .pickupcontainer__productHead
      新着ブランド
    .lists
      = render 'item_list_with_brand'
.fixedButton
  %p 出品する
  .fixedButton__image
    = link_to 'items/new' do
      =image_tag('icon/icon_camera.png', alt: "出品ボタン")
= render 'shared/bottomBanner'
= render 'shared/footer'

app/views/items/new.html.haml
.SellingPage
  .SellingPage__header
    .SellingPage__header__icon
      = link_to root_path do
        = image_tag('logo/logo.png', alt: "ヘッダーロゴ")
  .SellingPage__content
    .SellingPage__content__form
      = form_for(@item) do |f|
        = render 'shared/error_form', locals: { item: @item }
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 出品画像
              .FormField__label__title--must 必須

          %h1 最大5枚までアップロードできます
          .post__drop__box__container
            .prev-content
            .label-content
              %label{for: "item_item_images_attributes_0_src", class: "label-box", id: "label-box--0"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :item_images do |i|
                = i.file_field :src, class:"hidden-field", type: "file", name: "item[item_images_attributes][0][src]", id: "item_item_images_attributes_0_src"
                = i.file_field :image, class:"hidden-field", type: "file", name: "item[item_images_attributes][1][src]", id: "item_item_images_attributes_1_src"
                = i.file_field :image, class:"hidden-field", type: "file", name: "item[item_images_attributes][2][src]", id: "item_item_images_attributes_2_src"
                = i.file_field :image, class:"hidden-field", type: "file", name: "item[item_images_attributes][3][src]", id: "item_item_images_attributes_3_src"
                = i.file_field :image, class:"hidden-field", type: "file", name: "item[item_images_attributes][4][src]", id: "item_item_images_attributes_4_src"

        .Underline
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 商品名
              .FormField__label__title--must 必須
          .FormField__input
            = f.text_field :product_name, class: 'FormField__input--short', placeholder: '40文字まで'
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 商品の説明
              .FormField__label__title--must 必須
          .FormField__input
            = f.text_area :description, class: 'FormField__input--long', placeholder: '商品の説明（必須1,000文字以内)&#13;&#10;(色、素材、重さ、定価、注意点など)&#13;&#10;&#13;&#10;例) 2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。'.html_safe
        .Underline
        .FormField
          %h1 商品の詳細
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name カテゴリー
              .FormField__label__title--must 必須

          .FormField__input#category_box
            .pulldown#partent_box
              = f.collection_select :category_id, @parents.all, :id, :name, {include_blank: "選択してください"}, {class: "FormField__input--short", id: "parent_category", name: ""}

            .pulldown.item_input__body__category__children#children_box
              -#親カテゴリー選択によって子カテゴリー表示
            .pulldown.item_input__body__category__grandchildren#grandchildren_box
              -#子カテゴリー選択によって孫カテゴリー表示

        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name ブランド
              .FormField__label__title--free 任意
          .FormField__input
            = f.fields_for :brand do |i|
              = i.text_field :brand_name, class: 'FormField__input--short', placeholder: '例）シャネル'
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 商品の状態
              .FormField__label__title--must 必須
          .FormField__input
            = f.collection_select :condition_id, Condition.all, :id, :name, {include_blank: "選択してください"}, {class: "FormField__input--short"}
        .Underline
        .FormField
          %h1 配送について
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 配送料の負担
              .FormField__label__title--must 必須
          .FormField__input
            = f.collection_select :shipping_fee_id, ShippingFee.all, :id, :name, {include_blank: "選択してください"}, {class: "FormField__input--short"}
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 発送元の地域
              .FormField__label__title--must 必須
          .FormField__input
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: "選択してください"}, {class: "FormField__input--short"}
        .FormField
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 発送までの日数
              .FormField__label__title--must 必須
          .FormField__input
            = f.collection_select :day_to_ship_id, DayToShip.all, :id, :name, {include_blank: "選択してください"}, {class: "FormField__input--short"}
        .Underline
        .FormField
          %h1 価格（¥300〜¥9,999,999）
          .FormField__label
            .FormField__label__title
              .FormField__label__title__name 販売価格
              .FormField__label__title--must 必須
            .FormField__label__price
              ¥
              = f.number_field :price, class: 'FormField__label__price__value'
        .Submit
          = f.submit '出品する', class: 'Submit__btn'
        .Notice 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  .SellingPage__footer
    .SellingPage__footer__icon
      = link_to root_path do
        = image_tag('logo/logo.png', alt: "フッターロゴ")

app/views/items/show.html.haml
= render 'shared/header'
.page
  .page__content
    .item
      .item__content
        %h2.item__content--subtitle
          = @item.product_name
        .item__content--image
          .image__big
            = image_tag @item.item_images[0].src.url
          %ul
            %li.image__small
              - if @item.item_images[0].present?
                = image_tag @item.item_images[0].src.url
              - else 
                .image__small__none 
            %li.image__small
              - if @item.item_images[1].present?
                = image_tag @item.item_images[1].src.url
              - else 
                .image__small__none 画像無し
            %li.image__small
              - if @item.item_images[2].present?
                = image_tag @item.item_images[2].src.url
              - else 
                .image__small__none 画像無し 
            %li.image__small
              - if @item.item_images[3].present?
                = image_tag @item.item_images[3].src.url
              - else 
                .image__small__none 画像無し
            %li.image__small
              - if @item.item_images[4].present?
                = image_tag @item.item_images[4].src.url
              - else 
                .image__small__none 画像無し
        .item__content--price
          ¥
          = @item.price
        %p (税込)送料込み
        .item__content--description
          = @item.description
        .item__content--table
          %table
            %tr 
              %th 出品者
              %td 
                = @user_nickname
            %tr 
              %th カテゴリー
              %td.colorBlue
                = link_to "#{@category_parent.name}"
                %br/
                = link_to "#{@category_child.name}"
                %br/
                = link_to "#{@category_grandchild.name}"
            %tr
              %th ブランド
              %td 
                = @item.brand.brand_name
            %tr
              %th 商品の状態
              %td 
                = Condition.find(@item.condition_id).name
            %tr
              %th 配送料の負担
              %td 
                = ShippingFee.find(@item.shipping_fee_id).name
            %tr
              %th 発送元の地域
              %td 
                = Prefecture.find(@item.prefecture_id).name
            %tr
              %th 発送日の目安
              %td 
                = DayToShip.find(@item.day_to_ship_id).name

        .item__buttons
          .item__buttons--likeButton
            = link_to '#' do
              <i class="far fa-heart"></i> お気に入り
          .item__buttons--reportButton
            %a(href="#")
              <i class="fas fa-flag"></i>
              不適切な商品の通報
        .item__content--purchaseButton
          -if @purchase.blank?
            = link_to '購入画面に進む', new_item_purchase_path(@item.id), class: 'GoToPurchase'
          -else
            .SoldOut SOLD OUT
      .item__comment
        = form_with url: "#" do |form|
          = form.text_area :email
          %p
            相手のことを考え丁寧なコメントを心がけましょう。
            %br 不快な言葉遣いなどは利用制限や退会処分となることがあります。
          = button_tag type: 'submit' do
            = link_to '#' do
              <i class="fas fa-comment"></i> コメントする
        
      .item__select
        .item__select--previousButton
          = link_to item_path(@item.id-1) do
            < 前の商品
        .item__select--nextButton
          = link_to item_path(@item.id+1) do
            次の商品 >

.fixedButton
  %p 出品する
  .fixedButton__image
    = link_to new_item_path do
      =image_tag('icon/icon_camera.png', alt: "出品ボタン")
= render 'shared/bottomBanner'
= render 'shared/footer'