config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  get 'mypage', to: 'welcome#mypage'
  get 'signout', to: 'welcome#signout'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  resources :addresses, only: [:edit, :update]

  resources :welcome, only: [:index]
  resources :purchases, only: [:index]

  resources :items do
    resources :purchases, only: [:new, :create]
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  resources :cards, only: [:show, :new, :create, :destroy]
  
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user, optional: true
  validates :customer_id, :card_id, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require 'payjp'
  before_action :authenticate_user!, :set_category, :set_cards
  before_action :payjp_api, except: [:new]
  
  def new
    if @cards.exists?
      redirect_to card_path(@cards.first.id)
    end
  end

  def create
    customer = Payjp::Customer.create(card: params[:payjp_token])
    @card = Card.new(
      user_id:     current_user.id, 
      customer_id: customer.id, 
      card_id:     customer.default_card
    )
      if @card.save
        redirect_to action: "new"
      else
        redirect_to new_card_path
      end
  end

  def show
    if @cards.blank?
      redirect_to action: new
    else
      card = @cards.first
      customer = Payjp::Customer.retrieve(card.customer_id)
      @card_info = customer.cards.retrieve(card.card_id)
    end
  end

  def destroy
    if @cards.blank?
      redirect_to action: new
    else
      card = @cards.first
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  private
  def set_category
    @parents = Category.where(ancestry: nil)
  end

  def payjp_api
    Payjp.api_key = Rails.application.credentials[:payjp_secret_key]
  end

  def set_cards
    @cards = current_user.cards
  end

end

app/views/cards/new.html.haml
= render 'shared/header'
.UserMyPage
  .UserMyPage__content
    = render 'welcome/sidebar'
    .CardFormPage
      .CardFormPage__content
        .CardFormPage__content__title クレジットカード情報入力
        .Underline
        .CardFormPage__content__form
          = form_with url: cards_path, id: 'card-registration' do |f|
            .FormField
              .FormField__label
                .FormField__label__title
                  .FormField__label__title__name カード番号
                  .FormField__label__title--must 必須
              .FormField__input
                = f.number_field :number, class: 'FormField__input--short', id: 'card-number', placeholder: '半角数字のみ'
            .FormField
              .FormField__label
                .FormField__label__title
                  .FormField__label__title__name 有効期限
                  .FormField__label__title--must 必須
              .FormField__input
                .FormField__input__month
                  = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'FormField__input__month--xx', id: 'card-expire-month'
                  %h2 月
                .FormField__input__year
                  = f.select :exp_year, [["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029],["30",2030]],{} , class: 'FormField__input__year--xx', id: 'card-expire-year'
                  %h2 年
            .FormField
              .FormField__label
                .FormField__label__title
                  .FormField__label__title__name セキュリティコード
                  .FormField__label__title--must 必須
              .FormField__input
                = f.number_field :cvc, class: 'FormField__input--short', id: 'card-cvc', placeholder: 'カード背面4桁もしくは3桁の番号'
            .Submit
              = f.submit '追加する', id: 'card-save', class: 'Submit__btn'
            .Back
              = link_to 'もどる', '/', class: 'Back__text'
= render 'shared/bottomBanner'
= render 'shared/footer'

app/views/cards/show.html.haml
= render 'shared/header'
.UserMyPage
  .UserMyPage__content
    = render 'welcome/sidebar'
    .UserMyPage__content__main
      .MainContent
        .MainContent__title
          %h1.MainContent__title__text 登録されているカード
        .Underline
        .Card
          .Card__Info
            .Card__Info__brand
              = @card_info.brand
            .Card__Info__number
              **** **** ****
              = @card_info.last4
            .Card__Info__exp
              %h2 有効期限
              .Card__Info__exp__month
                = sprintf("%02d", @card_info.exp_month)
              %h2 /
              .Card__Info__exp__year
                = @card_info.exp_year - 2000
          .Card__delete
            = link_to '削除する', card_path(@cards.first.id), method: :delete, class: 'btn'
        .Underline
= render 'shared/bottomBanner'
= render 'shared/footer'